import type { CollectibleItem } from "@/lib/data"
import { isBoxTag } from "@/lib/tags"

// Slim shape shipped to the client for the archive listing.
// Full records (description, links) are fetched per item from /api/item/[id].
export type CatalogEntry = {
  id: string
  no: number
  name: string
  series: string
  work: string
  maker: string
  scale: string
  price: string
  year: string
  addedAt: string
  imageUrl: string
  thumb: string
  tags: string[]
  box?: string
  favorite?: boolean
  note?: string
}

// Same maker is spelled several ways across entries (katakana / romaji / case).
const MAKER_ALIASES: [RegExp, string][] = [
  [/^(bandai|バンダイ)/i, "BANDAI"],
  [/^(good ?smile|グッドスマイル)/i, "Good Smile"],
  [/^(takara|タカラトミー)/i, "Takara Tomy"],
  [/^(megahouse|メガハウス)/i, "MegaHouse"],
  [/^(banpresto|バンプレスト)/i, "Banpresto"],
  [/^(alter|アルター)/i, "Alter"],
  [/^animester/i, "AniMester"],
  [/^(yamato|ヤマト)/i, "Yamato"],
  [/^moshow ?toys/i, "Moshow Toys"],
  [/^(arcadia|アルカディア)/i, "Arcadia"],
  [/^(kotobukiya|コトブキヤ|壽屋)/i, "Kotobukiya"],
  [/^(sentinel|千値練)/i, "Sentinel"],
  [/^(max ?factory|マックスファクトリー)/i, "Max Factory"],
  [/^(kaiyodo|海洋堂)/i, "Kaiyodo"],
  [/^(volks|ボークス)/i, "Volks"],
  [/^(furyu|フリュー)/i, "FuRyu"],
  [/^(sega|セガ)/i, "SEGA"],
  [/^(taito|タイトー)/i, "TAITO"],
  [/^(freeing|フリーイング)/i, "FREEing"],
]

export function makerGroup(manufacturer: string) {
  const base = manufacturer.split(/[（(／/]/)[0].trim()
  for (const [re, name] of MAKER_ALIASES) if (re.test(base)) return name
  return base
}

// Series label for tight spaces: drop the bracketed English/alt titles.
export function shortSeries(series: string) {
  return series.replace(/\s*[（(][^）)]*[）)]\s*/g, " ").trim() || series
}

export function releaseYear(releaseDate: string) {
  return releaseDate.match(/(19|20)\d{2}/)?.[0] ?? "—"
}

export function buildCatalog(collection: CollectibleItem[]): CatalogEntry[] {
  // Catalogue number = order of acquisition (stable for same-day entries).
  const ordered = collection
    .map((item, i) => ({ item, i }))
    .sort((a, b) => a.item.addedAt.localeCompare(b.item.addedAt) || a.i - b.i)

  return ordered.map(({ item }, idx) => ({
    id: item.id,
    no: idx + 1,
    name: item.name,
    series: item.series,
    work: shortSeries(item.series),
    maker: makerGroup(item.manufacturer),
    scale: item.scale,
    price: item.price,
    year: releaseYear(item.releaseDate),
    addedAt: item.addedAt,
    imageUrl: item.imageUrl,
    thumb: thumbFor(item.imageUrl),
    tags: item.tags,
    box: item.tags.find(isBoxTag),
    ...(item.favorite ? { favorite: true } : {}),
    ...(item.note ? { note: item.note } : {}),
  }))
}

// Listing thumbnails are generated by scripts/thumbs.mjs at build time.
export function thumbFor(imageUrl: string) {
  const m = imageUrl.match(/^\/images\/(.+)\.(jpe?g|png|webp)$/i)
  return m ? `/thumbs/${m[1]}.webp` : imageUrl
}

export function formatNo(no: number) {
  return String(no).padStart(4, "0")
}
